github: [chris-short]
patreon: devopsish
custom: ["paypal.me/devopsish", devopsish.com, chrisshort.net, kubereadme.com, kubenews.net, devopsreadme.xyz, devopsnewsletters.com, nomedium.dev, padbury.app, crashloopbackoff.dev]