stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-production:
  stage: build
  environment:
    name: production
    url: https://preview.chrisshort.net
  artifacts:
    paths:
      - public
    expire_in: 1d
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - apk --no-cache update
    - apk --no-cache add git
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --minify --config config.toml
  only:
    - master

build-preview:
  stage: build
  environment:
    name: preview
    url: https://preview.chrisshort.net
  artifacts:
    paths:
      - public
    expire_in: 1d
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - apk --no-cache update
    - apk --no-cache add git
    - rm -rf public || exit 0
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - hugo --buildDrafts --buildFuture --config config-preview.toml
  except:
    - master

deploy-production:
  stage: deploy
  environment:
    name: production
    url: https://chrisshort.net
  artifacts:
    paths:
      - public
    expire_in: 1d
  image: quay.io/chrisshort/firebase:latest
  script:
    - firebase deploy --only hosting --token ${FIREBASE_TOKEN}
  only:
    - master

deploy-preview:
  stage: deploy
  environment:
    name: production
    url: https://preview.chrisshort.net
  artifacts:
    paths:
      - public
    expire_in: 1d
  image: quay.io/chrisshort/firebase:latest
  script:
    - firebase deploy --only hosting --token ${FIREBASE_TOKEN}
  except:
    - master