stages:
  - test
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: registry.gitlab.com/pages/hugo:latest

compile:
  stage: test
  before_script:
    - rm -rf public || exit 0
  script:
    - hugo --buildDrafts --buildFuture

pages:
  stage: build
  environment:
    name: preview
  before_script:
    - rm -rf public || exit 0
  script:
    - hugo --buildDrafts --buildFuture
  artifacts:
    paths:
    - public
  expire_in: 1h
  except:
    - master

gcp-build:
  stage: build
  environment:
    name: production
    url: chrisshort.net
  artifacts:
    paths:
      - public
    expire_in: 1h
  image: registry.gitlab.com/pages/hugo:latest
  before_script:
    - rm -rf public || exit 0
  script:
    - hugo
  only:
    - master

gcp-deploy:
  stage: deploy
  environment:
    name: gcs
    url: chrisshort.net
  image: google/cloud-sdk:alpine
  before_script:
    - echo -n ${GCS_TOKEN} | base64 -d > ${GCS_TOKEN_FILE}
    - gcloud config set project ${GCS_PROJECT}
    - gcloud auth activate-service-account --key-file ${GCS_TOKEN_FILE}
  script:
    - gsutil -m rsync -a public-read -d -r public gs://${CI_PROJECT_NAME}/
  only:
    - master
