baseurl: "https://chrisshort.net"
DefaultContentLanguage: en
title: chrisshort.net
theme: PaperMod
pygmentsStyle: trac
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
paginate: 5
permalinks:
    post: ":title/"
Params:
    homeInfoParams:
        Title: Chris Short
        Content: >
            Kubernetes | Voice of Hybrid Cloud on OpenShift.tv, Red Hat | CNCF
            Ambassador + @KubeWeekly | devopsish.com | Disabled Veteran | He/Him/His |
            Views solely mine

    socialIcons:
        - name: email
          url: mailto:chris@chrisshort.net
        - name: github
          url: https://github.com/chris-short
        - name: twitter
          url: https://twitter.com/ChrisShort
        - name: reddit
          url: https://reddit.com/u/oaf357
        - name: linkedin
          url: https://www.linkedin.com/in/thechrisshort
        - name: youtube
          url: https://www.youtube.com/channel/UC8jhUEJ-K_QfDWbmpmwi4XA
        - name: telegram
          url: https://telegram.me/ChrisShort
        - name: twitch
          url: https://twitch.tv/redhatopenshift
        - name: rss
          url: https://chrisshort.net/index.xml

    mainSections:
        - post
        - posts

    comments: false
    gcse: "partner-pub-8972983586873269:7437701092"
    selfHosted: true
    ShowReadingTime: true
Author:
    name: Chris Short
    website: "https://chrisshort.net"
    email: chris@chrisshort.net
    github: chris-short
    devto: chrisshort
    twitter: ChrisShort
    reddit: oaf357
    linkedin: thechrisshort
    youtube: channel/UC8jhUEJ-K_QfDWbmpmwi4XA
    telegram: ChrisShort
    twitch: redhatopenshift

privacy:
    disqus:
        disable: true
    googleAnalytics:
        disable: true
    instagram:
        disable: false
        simple: false
    twitter:
        disable: false
        enableDNT: true
        simple: false
    vimeo:
        disable: false
        simple: false
    youtube:
        disable: false
        privacyEnhanced: true

menu:
    main:
        - name: Search
          url: search

# for search to work
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
