baseurl: "https://chrisshort.net"
DefaultContentLanguage: en
title: ChrisShort.net
theme: PaperMod
pygmentsStyle: trac
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
paginate: 5
Copyright: "[Some rights reserved](/copyright/) © 2003 - 2021 [Chris Short](https://linktr.ee/TheChrisShort) • [Terms](/terms/) • [Privacy](/privacy) • [Cookies](/cookie-policy/)"
permalinks:
    post: ":title/"
Params:
    # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#enable-social-metadata-and-seo
    env: production
    label:
        icon: /favicon-32x32.png
        favicon16x16: /favicon-16x16.png
        favicon32x32: /favicon-32x32.png
        apple_touch_icon: /apple_icon.png
        safari_pinned_tab: /safari_pinned_tab.svg

    homeInfoParams:
        Title: Chris Short
        Content: >
            Kubernetes | Dev 🥑 Amazon EKS | CNCF Ambassador + KubeWeekly | devopsish.com | Disabled Veteran | 
            He/Him/His | Views solely mine

    socialIcons:
        - name: email
          url: mailto:chris@chrisshort.net
        - name: github
          url: https://github.com/chris-short
        - name: twitter
          url: https://twitter.com/ChrisShort
        - name: reddit
          url: https://reddit.com/u/oaf357
        - name: linkedin
          url: https://www.linkedin.com/in/thechrisshort
        - name: youtube
          url: https://www.youtube.com/channel/UCMzMqbKmCmUZWAmV8jr8Daw
        - name: telegram
          url: https://telegram.me/ChrisShort
        - name: rss
          url: https://chrisshort.net/index.xml

    mainSections:
        - post
        - posts

    gcse: "partner-pub-8972983586873269:7437701092"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true

privacy:
    disqus:
        disable: true
    googleAnalytics:
        disable: true
    instagram:
        disable: false
        simple: false
    twitter:
        disable: false
        enableDNT: true
        simple: false
    vimeo:
        disable: false
        simple: false
    youtube:
        disable: false
        privacyEnhanced: true

menu:
    main:
        - name: About
          url: about
          weight: 1
        - name: Speaking
          url: speaking
          weight: 2
        - name: Interviews
          url: interviews
          weight: 3
        - name: Archive
          url: archive
          weight: 4
        - name: Search
          url: search
          weight: 5

# for search to work
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
    goldmark:
        renderer:
            unsafe: true
