baseurl: "https://chrisshort.net"
DefaultContentLanguage: en
title: ChrisShort.net
theme: PaperMod
pygmentsStyle: trac
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
paginate: 8
permalinks:
    post: ":title/"
Params:
    # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#enable-social-metadata-and-seo
    env: production
    label:
        icon: /favicon-32x32.png
        favicon16x16: /favicon-16x16.png
        favicon32x32: /favicon-32x32.png
        apple_touch_icon: /apple_icon.png
        safari_pinned_tab: /safari_pinned_tab.svg

    homeInfoParams:
        Title: Chris Short
        Content: >
            Open Source Diplomat | Kubernetes Contributor | Disabled Veteran (definitely in pain) | Detroit | Kubernetes at AWS | He/Him/His | Views solely mine

    socialIcons:
        - name: github
          url: https://github.com/chris-short
        - name: linkedin
          url: https://www.linkedin.com/in/thechrisshort
        - name: twitch
          url: https://www.twitch.tv/thechrisshort
        - name: youtube
          url: https://www.youtube.com/c/ChrisShort
        - name: tumblr
          url: https://chrisshort.tumblr.com/
        - name: reddit
          url: https://www.reddit.com/r/devopsish/
        - name: mastodon
          url: https://hachyderm.io/@ChrisShort
        - name: twitter
          url: https://twitter.com/ChrisShort
        - name: email
          url: mailto:chrisshort@duck.com
        - name: rss
          url: https://chrisshort.net/index.xml

    mainSections:
        - post
        - posts

    gcse: "partner-pub-8972983586873269:7437701092"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: true
    defaultTheme: light
    disableThemeToggle: true
    disableScrollToTop: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: true

imaging:
  resampleFilter: box
  anchor: smart
  bgColor: '#ffffff'
  disableLatLong: true
  exif:
    includeFields: ''

privacy:
    disqus:
        disable: true
    googleAnalytics:
        disable: true
    instagram:
        disable: false
        simple: false
    twitter:
        disable: false
        enableDNT: true
        simple: false
    vimeo:
        disable: false
        simple: false
    youtube:
        disable: false
        privacyEnhanced: true

menu:
    main:
        - name: About
          url: about
          weight: 1
        - name: Speaking
          url: speaking
          weight: 2
        - name: Interviews
          url: interviews
          weight: 3
        - name: Archive
          url: archive
          weight: 4
        - name: Search
          url: search
          weight: 5

# for search to work
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
    goldmark:
        renderer:
            unsafe: true
