# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "hugo"
  publish = "public/"
[context.production.environment]
  HUGO_VERSION = "0.27.1"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "hugo"
  publish = "public/"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.27.1"
