[build]
  command = "hugo"
  publish = "public"

# Change the version of Hugo you want to use on Netlify
# by changing this environment variable.
[build.environment]
  HUGO_VERSION = "v0.25.1"

[context.deploy-preview]
  command = "hugo"
  branch = "preview"
