[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.104.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.split1]
command = "curl -L 'https://cdn.carbonads.com/carbon.js?serve=CK7D52QU&placement=chrisshortnet' -o assets/js/extended/carbon.js || hugo --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.104.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -DF -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.104.0"
# Skip all post processing in deploy previews,
# ignoring any other settings
[context.deploy-preview.processing]
  skip_processing = true

[context.branch-deploy]
command = "hugo -DF -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.104.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"

# https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing
# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[redirects]]
  from = "https://chrisshort.netlify.app/*"
  to = "https://chrisshort.net/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = 'https://chrisshort.net'
    Permissions-Policy = 'accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()'
    Referrer-Policy = 'no-referrer-when-downgrade'
    Strict-Transport-Security = 'max-age=63072000; includeSubDomains; preload'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'