[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.split1]
command = "curl -L 'https://cdn.carbonads.com/carbon.js?serve=CK7D52QU&placement=chrisshortnet' -o assets/js/extended/carbon.js && hugo --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "curl -L 'https://cdn.carbonads.com/carbon.js?serve=CK7D52QU&placement=chrisshortnet' -o assets/js/extended/carbon.js && hugo --gc -DF -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_VERSION = "0.82.0"
# Skip all post processing in deploy previews,
# ignoring any other settings
[context.deploy-preview.processing]
  skip_processing = true

[context.branch-deploy]
command = "curl -L 'https://cdn.carbonads.com/carbon.js?serve=CK7D52QU&placement=chrisshortnet' -o assets/js/extended/carbon.js && hugo --gc -DF -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
HUGO_VERSION = "0.82.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"

# https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing
# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[redirects]]
  from = "https://chrisshort.netlify.app/*"
  to = "https://chrisshort.net/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = 'fullscreen=(self "https://chrisshort.net"), geolocation=(), camera=(), microphone=()'
