---
name: Site Build
on:
  schedule:
  - cron: '0 7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      env:
        TOKEN: ${{ secrets.HOOK }}
      run: >-
          curl -X POST "${HOOK}"
